global using Blazr.App.Core;
global using Blazr.Core.OWS;
global using Blazr.OneWayStreet.Core;
global using Blazr.OneWayStreet.Infrastructure;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
