<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Libraries\Blazr.Diode\Blazr.Diode.csproj" />
	  <ProjectReference Include="..\..\Libraries\Blazr.Cadmium\Blazr.Cadmium.csproj" />
	  <ProjectReference Include="..\..\Libraries\Blazr.Indium\Blazr.Indium.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="WeatherForecasts\DomainEntities\" />
	  <Folder Include="WeatherForecasts\Entity\EntityObjects\" />
	</ItemGroup>

</Project>
