<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="WeatherForecasts\Requests\WeatherForecastEntityCommandRequest.cs~RF2269b278.TMP" />
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Libraries\Blazr.Diode\Blazr.Diode.csproj" />
	  <ProjectReference Include="..\..\Libraries\Blazr.Cadmium\Blazr.Cadmium.csproj" />
	  <ProjectReference Include="..\..\Libraries\Blazr.Indium\Blazr.Indium.csproj" />
	  <ProjectReference Include="..\..\Libraries\Blazr.Manganese\Blazr.Manganese.csproj" />
	</ItemGroup>

</Project>
