global using Blazr.App.Core;
global using Blazr.App.Infrastructure;
global using Blazr.Diode;
global using Blazr.Diode.Infrastructure.EntityFramework;
global using Blazr.Diode.Mediator;
global using Blazr.Gallium;
global using Blazr.Manganese;
global using Microsoft.EntityFrameworkCore;
global using System.Linq.Expressions;
