global using Blazr.BaseComponents;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.AspNetCore.Components.QuickGrid;
global using Microsoft.AspNetCore.Components.Rendering;
global using System.Collections;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq.Expressions;
global using System.Text;
